//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gerente
    {
        public Gerente()
        {
            this.Proyecto = new HashSet<Proyecto>();
            this.Factor = new HashSet<Factor>();
        }
    
        public int DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual ICollection<Factor> Factor { get; set; }
    }
}
