//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloDatosContainer : DbContext
    {
        public ModeloDatosContainer()
            : base("name=ModeloDatosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gerente> Gerente { get; set; }
        public DbSet<Proyecto> Proyecto { get; set; }
        public DbSet<Factor> Factor { get; set; }
        public DbSet<Valor> Valor { get; set; }
        public DbSet<Ponderacion> Ponderacion { get; set; }
    }
}
